import Head from 'next/head'
import Layout from '@Layout/mainLayout';
import dynamic from 'next/dynamic';
const SliderRegular = dynamic(()=>import('@components/Common/Slider/sliderRegular'));
const AreaExpert = dynamic(()=>import('@components/AreaExpert'));
const OwnClients = dynamic(()=>import('@components/OwnClients/index'));
const DescriptionQC = dynamic(()=>import('@components/DescriptionQC'));
const AllProyects = dynamic(()=>import('@components/Allproyects'));
const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="marginHeader"></div>
      <SliderRegular
      banners={[
        {
          image: {
            web: 'https://rockstheme.com/rocks/randerc-preview/img/background/bg.jpg',
            mobile: 'https://rockstheme.com/rocks/randerc-preview/img/background/bg.jpg'
          }
        }
      ]}      
      />
      <AreaExpert />
      <DescriptionQC />
      <AllProyects />
      <OwnClients />      
    </div>
  )
}

Home.Layout = Layout;

export default Home
